# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Subject Matter Expert Qualification Assessments
email: DL.OMB.SMEQA@omb.eop.gov
description: >- # this means to ignore newlines until "baseurl:"
  The United States Digital Service is transforming federal hiring. Our SME-QA process helps agencies improve their assessment of job candidates within the competitive hiring process and upholds the merit systems princples.
baseurl: "https://smeqa.usds.gov"

styles: styles.min.css
print-styles: print-styles.min.css
hiring-action-styles: hiring-action.min.css

url: "https://smeqa.usds.gov" # the base hostname & protocol for your site, e.g. http://example.com
author: U.S. Digital Service

repository: usds/SME-QA-Website

github_url: https://github.com/usds/SME-QA-Website/

# Build settings
markdown: kramdown

# Plugins
plugins:
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

last-modified-at:
  date-format: '%B %d, %Y'

# Jekyll SEO Tag
# See https://github.com/jekyll/jekyll-seo-tag
logo: /img/usds-logo-onwhite.png

# Google Analytics - Gov wide account
analytics_id: "UA-132706295-1"

collections:
  hr-tasks:
    output: true
  sme-tasks:
    output: true
  toolkit:
    output: true

# Exclude from processing.
exclude:
  - ".ruby-version"
  - ".sass-cache"
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - config
  - js
  - vendor
  - manifest.yml
  - node_modules
  - package.json
  - gulpfile.js
  - circle.yml
  - css
  - compressing.sh
  - package-lock.json
